---
name: "Update CLI Reference Docs"

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  cli-ref-docs:
    name: Update CLI Reference Docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout docs
        uses: actions/checkout@v3

      - name: Install Updatecli Binary
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli in enforce mode
        run: "updatecli compose apply --file updatecli/update-cli-ref-docs.yaml"
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
